### ISSUE TITLE
License clarification requested

### ISSUE THREAD

**Issue by KingMob** [thaines/helit#3]
Hi, in the README for handwriting you say that you use "GNU Affero GPL 3.0 for the bits we want to license (research use is OK, but commercial use would be extremely problematic)". However, the Gnu Affero GPL 3 license doesn't place any restrictions on commercial use (as long as modified source code is offered).

I'm asking because I work for a small startup that's contemplating adding handwritten notes to our greeting card/sharing service we're launching. We came across Handwriting.io and it looked neat but pricy, so we started hunting around for other possibilities and found this.

I don't want to step on any toes, but it's not clear if you're actually trying to prohibit commercial use of the handwriting library or not.

**Comment by thaines** [comment]
You're entirely right that, as long as you share your modifications with
the users, you will have satisfied the license requirements, and can do so
commercially if you wish. That's absolutely fine. It's done this way
because we have an obligation to publish the code, so that other
researchers can build on it, but also an obligation to let the uni make
money off of our work - this is effectively a 'poison pill' type approach
to achieving both aims are the same time, as most companies would not be
willing to integrate such a license into their systems. Part of this is
that the code is a long way from something that can be used commercially -
you're almost certainly looking at months of effort to get it into that
state, and then you have to give all of that work away to the world, and
all of your competitors - spending money for no advantage. The other part
is the need to silo that code from the rest, making sure there is no risk
of doing anything that requires you to release other aspects of your
companies code base, which can be fiddly to get right. Of course, you may
decide that you're willing to live with these issues.

**Comment by KingMob** [comment]
Thanks for the clarification! 

And thank you for sharing your work. I used to be an academic in cognitive neuroscience, and found it sad to see everyone hoarding their code.

Best of luck.
